### ISSUE TITLE
Installation Labs

### ISSUE THREAD

**Issue by santosh015** [santosh015/SEBC#2]

**Comment by santosh015** [comment]
Pre-installation check done on all the nodes.

**Comment by santosh015** [comment]
Now started Mysql Replica Creation.

**Comment by santosh015** [comment]
Mysql replica created.

**Comment by santosh015** [comment]
CM installation started.

**Comment by santosh015** [comment]
CM install complete.

**Comment by mfernest** [comment]
Please name these Issues as directed in the README.

**Comment by mfernest** [comment]
👍
